name: ci
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install the latest version of uv and set the python version to 3.12
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"

      - run: uv run mkdocs gh-deploy --force
